/** @type {import('tailwindcss').Config} */
// 使用tailwindcss 预设颜色
import colors from "tailwindcss/colors";

export default {
    darkMode: 'class',//手动切换深色模式
    content: ["./system.html", "./src/**/*.{js,ts,jsx,tsx}",],
    //自定义颜色
    theme: {
        extend: {
            fontFamily: {
                // buddha: ["Buddha"],
                // fish: ["Fish"],
                // sb: ["HuXiaoBao-SaoBao"],
                // ns: ["HuXiaoBao-NanSheng"],
                // zs: ["HuXiaoBao-ZhengShuai"],
                // stone: ["Stone"],
                // xl: ["XiaoLai"],
                // alimaDL: ["AlimamaDaoLi"],
                // alimaLD: ["AlimamaAgile"],
            },
            screens: {
                xs: '480px',
                sm: '576px',
                md: '768px',
                lg: '992px',
                xl: '1200px',
                '2xl': '1600px',
            },
            colors: {
                teal: colors.teal,
                cyan: colors.cyan,
                "bun-blue": '#314659',
                "bun-gray": '#f5f3f2',
                "bun-bg-hover-dark": '#3f3f3fc4',
                "bun-bg-dark": "#222b36",
                hover: '#63738114',
                antd: {
                    bgBase: 'var(--ant-color-bg-base)',
                    textBase: 'var(--ant-color-text-base)',
                    primary: 'var(--ant-color-primary)',
                    primaryBg:'var(--ant-color-primary-bg)',
                    primaryText: 'var(--ant-color-primary-text)',
                    primaryTextHover: 'var(--ant-color-primary-text-hover)',
                    primaryBorderHover: 'var(--ant-color-primary-border-hover)',
                    primaryTextActive: 'var(--ant-color-primary-text-active)',
                    success: 'var(--ant-color-success)',
                    successText: 'var(--ant-color-success-text)',
                    successBorderHover: 'var(--ant-color-success-border-hover)',
                    successTextHover: 'var(--ant-color-success-text-hover)',
                    successTextActive: 'var(--ant-color-success-text-active)',
                    warning: 'var(--ant-color-warning)',
                    warningText: 'var(--ant-color-warning-text)',
                    warningBorderHover: 'var(--ant-color-warning-border-hover)',
                    warningTextHover: 'var(--ant-color-warning-text-hover)',
                    warningTextActive: 'var(--ant-color-warning-text-active)',
                    error: 'var(--ant-color-error)',
                    errorText: 'var(--ant-color-error-text)',
                    errorBorderHover: 'var(--ant-color-error-border-hover)',
                    errorTextHover: 'var(--ant-color-error-text-hover)',
                    errorTextActive: 'var(--ant-color-error-text-active)',
                    info: 'var(--ant-color-info)',
                    infoText: 'var(--ant-color-info-text)',
                    infoBorderHover: 'var(--ant-color-info-border-hover)',
                    infoTextHover: 'var(--ant-color-info-text-hover)',
                    infoTextActive: 'var(--ant-color-info-text-active)',
                    dark: {
                        layout: 'var(--ant-color-bg-layout)',
                        container: 'var(--ant-color-bg-container)',
                        elevated: 'var(--ant-color-bg-elevated)',
                    },
                    blue: {
                        1: 'var(--ant-blue-1)',
                        2: 'var(--ant-blue-2)',
                        3: 'var(--ant-blue-3)',
                        4: 'var(--ant-blue-4)',
                        5: 'var(--ant-blue-5)',
                        6: 'var(--ant-blue-6)',
                        7: 'var(--ant-blue-7)',
                        8: 'var(--ant-blue-8)',
                        9: 'var(--ant-blue-9)',
                        10: 'var(--ant-blue-10)',
                    },
                    purple: {
                        1: 'var(--ant-purple-1)',
                        2: 'var(--ant-purple-2)',
                        3: 'var(--ant-purple-3)',
                        4: 'var(--ant-purple-4)',
                        5: 'var(--ant-purple-5)',
                        6: 'var(--ant-purple-6)',
                        7: 'var(--ant-purple-7)',
                        8: 'var(--ant-purple-8)',
                        9: 'var(--ant-purple-9)',
                        10: 'var(--ant-purple-10)',
                    },
                    cyan: {
                        1: 'var(--ant-cyan-1)',
                        2: 'var(--ant-cyan-2)',
                        3: 'var(--ant-cyan-3)',
                        4: 'var(--ant-cyan-4)',
                        5: 'var(--ant-cyan-5)',
                        6: 'var(--ant-cyan-6)',
                        7: 'var(--ant-cyan-7)',
                        8: 'var(--ant-cyan-8)',
                        9: 'var(--ant-cyan-9)',
                        10: 'var(--ant-cyan-10)',
                    },
                    green: {
                        1: 'var(--ant-green-1)',
                        2: 'var(--ant-green-2)',
                        3: 'var(--ant-green-3)',
                        4: 'var(--ant-green-4)',
                        5: 'var(--ant-green-5)',
                        6: 'var(--ant-green-6)',
                        7: 'var(--ant-green-7)',
                        8: 'var(--ant-green-8)',
                        9: 'var(--ant-green-9)',
                        10: 'var(--ant-green-10)',
                    },
                    magenta: {
                        1: 'var(--ant-magenta-1)',
                        2: 'var(--ant-magenta-2)',
                        3: 'var(--ant-magenta-3)',
                        4: 'var(--ant-magenta-4)',
                        5: 'var(--ant-magenta-5)',
                        6: 'var(--ant-magenta-6)',
                        7: 'var(--ant-magenta-7)',
                        8: 'var(--ant-magenta-8)',
                        9: 'var(--ant-magenta-9)',
                        10: 'var(--ant-magenta-10)',
                    },
                    pink: {
                        1: 'var(--ant-pink-1)',
                        2: 'var(--ant-pink-2)',
                        3: 'var(--ant-pink-3)',
                        4: 'var(--ant-pink-4)',
                        5: 'var(--ant-pink-5)',
                        6: 'var(--ant-pink-6)',
                        7: 'var(--ant-pink-7)',
                        8: 'var(--ant-pink-8)',
                        9: 'var(--ant-pink-9)',
                        10: 'var(--ant-pink-10)',
                    },
                    red: {
                        1: 'var(--ant-red-1)',
                        2: 'var(--ant-red-2)',
                        3: 'var(--ant-red-3)',
                        4: 'var(--ant-red-4)',
                        5: 'var(--ant-red-5)',
                        6: 'var(--ant-red-6)',
                        7: 'var(--ant-red-7)',
                        8: 'var(--ant-red-8)',
                        9: 'var(--ant-red-9)',
                        10: 'var(--ant-red-10)',
                    },
                    orange: {
                        1: 'var(--ant-orange-1)',
                        2: 'var(--ant-orange-2)',
                        3: 'var(--ant-orange-3)',
                        4: 'var(--ant-orange-4)',
                        5: 'var(--ant-orange-5)',
                        6: 'var(--ant-orange-6)',
                        7: 'var(--ant-orange-7)',
                        8: 'var(--ant-orange-8)',
                        9: 'var(--ant-orange-9)',
                        10: 'var(--ant-orange-10)',
                    },
                    yellow: {
                        1: 'var(--ant-yellow-1)',
                        2: 'var(--ant-yellow-2)',
                        3: 'var(--ant-yellow-3)',
                        4: 'var(--ant-yellow-4)',
                        5: 'var(--ant-yellow-5)',
                        6: 'var(--ant-yellow-6)',
                        7: 'var(--ant-yellow-7)',
                        8: 'var(--ant-yellow-8)',
                        9: 'var(--ant-yellow-9)',
                        10: 'var(--ant-yellow-10)',
                    },
                    volcano: {
                        1: 'var(--ant-volcano-1)',
                        2: 'var(--ant-volcano-2)',
                        3: 'var(--ant-volcano-3)',
                        4: 'var(--ant-volcano-4)',
                        5: 'var(--ant-volcano-5)',
                        6: 'var(--ant-volcano-6)',
                        7: 'var(--ant-volcano-7)',
                        8: 'var(--ant-volcano-8)',
                        9: 'var(--ant-volcano-9)',
                        10: 'var(--ant-volcano-10)',
                    },
                    geekblue: {
                        1: 'var(--ant-geekblue-1)',
                        2: 'var(--ant-geekblue-2)',
                        3: 'var(--ant-geekblue-3)',
                        4: 'var(--ant-geekblue-4)',
                        5: 'var(--ant-geekblue-5)',
                        6: 'var(--ant-geekblue-6)',
                        7: 'var(--ant-geekblue-7)',
                        8: 'var(--ant-geekblue-8)',
                        9: 'var(--ant-geekblue-9)',
                        10: 'var(--ant-geekblue-10)',
                    },
                    gold: {
                        1: 'var(--ant-gold-1)',
                        2: 'var(--ant-gold-2)',
                        3: 'var(--ant-gold-3)',
                        4: 'var(--ant-gold-4)',
                        5: 'var(--ant-gold-5)',
                        6: 'var(--ant-gold-6)',
                        7: 'var(--ant-gold-7)',
                        8: 'var(--ant-gold-8)',
                        9: 'var(--ant-gold-9)',
                        10: 'var(--ant-gold-10)',
                    },
                    lime: {
                        1: 'var(--ant-lime-1)',
                        2: 'var(--ant-lime-2)',
                        3: 'var(--ant-lime-3)',
                        4: 'var(--ant-lime-4)',
                        5: 'var(--ant-lime-5)',
                        6: 'var(--ant-lime-6)',
                        7: 'var(--ant-lime-7)',
                        8: 'var(--ant-lime-8)',
                        9: 'var(--ant-lime-9)',
                        10: 'var(--ant-lime-10)',
                    },
                }
                // primary: 'var(--ant-color-primary)',
                // primary: 'var(--ant-color-primary)',
                // primary: 'var(--ant-color-primary)',
                // primary: 'var(--ant-color-primary)',
                // primary: 'var(--ant-color-primary)',
                // primary: 'var(--ant-color-primary)',
                // blue: {
                //     light: '#85d7ff',
                //     DEFAULT: '#1fb6ff',
                //     dark: '#009eeb',
                // },
            },
            animation: {
                wave: 'wave 1s ease-in-out infinite',
            },
            keyframes: {
                wave: {
                    "0% ": {
                        transform: 'scale(0)',
                        opacity: 1,
                    },
                    "15%": {
                        transform: 'scale(0)',
                    },
                    "20%": {
                        opacity: 1,
                    },
                    "100%": {
                        transform: "scale(1)",
                        opacity: 0,
                    }
                }
            }
        },
    },
}
